name: TDnet Daily Downloader

on:
  workflow_dispatch:
  schedule:
    # JST is UTC+9
    - cron: '31 6 * * 1-5' # 平日 15:31 JST
    - cron: '1 9 * * 1-5'  # 平日 18:01 JST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ▼▼▼ 変更点：正しいURLに修正 ▼▼▼
      - name: Run downloader script from Gist
        run: |
          # 正しいURLから最新版のコードをダウンロード
          curl -o downloader_latest.py https://gist.githubusercontent.com/GoogleCloudPlatform/225b60499b18337778b30e0173f40590/raw/downloader_auto.py
          # ダウンロードしたコードを実行
          python downloader_latest.py
      # ▲▲▲ ここまで ▲▲▲

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update downloaded files"
          file_pattern: "**/*.pdf"
